---
title: ""
format: 
  html: 
    css: styles.scss
    toc: false
    page-layout: full
---

### Recent Publications
Peter T. McLaughlin and Nathan T. Barron. Forthcoming. 
<font color="#E5625e">"Beyond Credit Claiming: Protection and Commiseration Messages in Distributive Politics."</font>
*Political Research Quarterly.* &nbsp;
<details style="margin-left: 40px;">
<summary>Abstract</summary>
> Credit claiming, where legislators highlight their role in bringing home federal spending projects to their district, has been shown to offer electoral value in an array of studies. However, congressional messaging on distributive politics expands beyond credit claiming. Distributive policy moves in two directions -- new spending and budget cuts -- leading to more types of messaging than are currently explored. Legislators often claim credit for protecting existing initiatives (protection messages) and speak out against decisions to cut district projects (commiseration messages). We develop a theory of distributive politics that incorporates the full range of congressional messaging on federal spending. Using an online survey experiment, we find that constituents are receptive to protection and commiseration messages. In fact, protection and commiseration messages are no less effective than traditional credit claims and announcement messages, respectively. These findings suggest distributive politics is about more than displaying influence; it provides legislators with a window for recognizing constituent needs, even in the absence of positive policy outcomes. 
</details>

Nathan T. Barron, Peter T. McLaughlin, H Benjamin Ashton III, Rachel Blum, Charles J. Finocchairo, and Michael H. Crespin. 2025. 
<font color="#E5625e">"Presidential Endorsements as Voter Cues: Evidence from the 2022 Midterm Elections."</font>
*Political Behavior.*&nbsp;
<a href="https://doi.org/10.1007/s11109-025-10061-3" target="_blank">{{< ai doi size=xl color="#C33C54" >}}</a>
<a href="https://doi.org/10.31235/osf.io/fr5ma_v1" target="_blank">{{< ai open-access size=xl color="#505A68" >}}</a>
<a href="https://doi.org/10.7910/DVN/FSZ7V6" target="_blank">{{< ai open-data size=xl color="#254E70" >}}</a>
<details style="margin-left: 40px;">
<summary>Abstract</summary>
> Presidential endorsements are coveted by Congressional candidates with the hopes of increasing electoral resources and improving electoral outcomes. However, not all presidential endorsements are beneficial to candidates at all times. For example, recent studies have shown that Donald Trump’s endorsements, in particular, had a negative impact on campaign resources during general elections. This research focuses on how presidential endorsements affect voter’s perceptions of and support for Congressional candidates. Using a preregistered survey experiment embedded in the 2022 Cooperative Election Study, we examine how respondents change ideological perceptions and support for a fictional candidate when presented with a presidential endorsement. We find that Trump endorsements carry a negative effect that is mediated by respondents’ ideological perceptions of the candidate. We corroborate these findings with observational analyses among verified voters in the 2022 midterm elections. Altogether, this paper offers a theoretical model that clarifies how this elite behavior impacts electoral decision-making.
</details>


Peter T. McLaughlin and Nathan T. Barron. 2025. 
<font color="#E5625e">"Credible Claims: The Effect of Committee Positioning on Congressional Credit Claiming."</font>
*American Politics Research.* 53(3): 275-286. &nbsp;
<a href="https://doi.org/10.1177/1532673X241309632" target="_blank">{{< ai doi size=xl color="#C33C54" >}}</a>
<a href="https://doi.org/10.31235/osf.io/cw5e4_v1" target="_blank">{{< ai open-access size=xl color="#505A68" >}}</a>
<a href="https://doi.org/10.7910/DVN/L2G0LA" target="_blank">{{< ai open-data size=xl color="#254E70" >}}</a>
<details style="margin-left: 40px;">
<summary>Abstract</summary>
> Members of Congress routinely seek to improve their institutional position to increase their influence over policy outcomes. Prominent among those policy outcomes is the distribution of federal spending projects, where members can simultaneously secure local particularistic spending and its consequential electoral benefits. While institutional position facilitates the receipt of these policy goods, it is less clear whether representatives’ position facilitates the receipt of the associated electoral benefits. We test whether a representative’s signaling of policy influence through references to committee positioning increases the effectiveness of credit claiming for particularistic spending. Using a survey experiment, we measure how respondents change their approval and effectiveness ratings for a member of Congress when presented with different versions of real-world credit claiming press releases. Overall, we find that signaling influence vis-à-vis committee positioning has an undetectable effect on the effectiveness of credit claiming. This research highlights an important challenge faced by members of Congress in publicizing their roles in favorable policy actions.
</details>
  

Peter T. McLaughlin, Peter Olson, Nathan T. Barron, H Benjamin Ashton III, Rachel Blum, Charles J. Finnocchiaro, and Michael H. Crespin. 2024. 
<font color="#E5625e">"Ends Versus Means: Public Opinion on Congressional Redistricting."</font>
*Election Law Journal.* &nbsp;
<a href="https://doi.org/10.1089/elj.2023.0050" target="_blank">{{< ai doi size=xl color="#C33C54" >}}</a>
<a href="https://doi.org/10.31235/osf.io/v87fn_v1" target="_blank">{{< ai open-access size=xl color="#505A68" >}}</a>
<a href="https://doi.org/10.7910/DVN/SEA61B" target="_blank">{{< ai open-data size=xl color="#254E70" >}}</a>
<details style="margin-left: 40px;">
<summary>Abstract</summary>
> State-level redistricting processes shape congressional elections and representation, and recent reform efforts have propelled congressional redistricting procedures into mainstream political discussion. We ask whether citizens’ satisfaction with redistricting in their state is shaped by ends (election results) or by means (type of redistricting process). Leveraging questions on the 2022 Cooperative Election Study, state-level variation in redistricting processes, and 2022 election outcomes, we find that both ends and means shape the public’s satisfaction with redistricting in their state. Among respondents who correctly identified their state’s redistricting process for the 2022 midterm elections, those living in a state with a redistricting commission reported greater support for redistricting than those living in a state with legislature-controlled redistricting. We also find that respondents who are represented by a copartisan in the U.S. House are more supportive of their state’s congressional redistricting process than both respondents who identify as independent and respondents who are represented by an opposing party legislator. Successful electoral reforms require public buy-in, and our results suggest that partisan power considerations and a lack of public knowledge about congressional redistricting present barriers to reforming state-level redistricting processes.
</details>


Nathan T. Barron and Peter T. McLaughlin. 2024. 
<font color="#E5625e">"Experimental Evidence of the Benefits and Risks of Credit Claiming and Pork Busting."</font>
*Legislative Studies Quarterly*, 49(1): 103-129. &nbsp;
<a href="https://doi.org/10.1111/lsq.12425" target="_blank">{{< ai doi size=xl color="#C33C54" >}}</a>
<a href="https://doi.org/10.31235/osf.io/7thuz_v1" target="_blank">{{< ai open-access size=xl color="#505A68" >}}</a>
<a href="https://doi.org/10.7910/DVN/ZUFWZM" target="_blank">{{< ai open-data size=xl color="#254E70" >}}</a>
<details style="margin-left: 40px;">
<summary>Abstract</summary>
> As appropriations earmarks return to Congress, every legislator faces a decision: pursue or refuse congressionally mandated federal spending projects. This decision is likely influenced by public messaging concerns. We theorize that both credit claiming for federal projects and position taking against spending projects (“pork busting”) can benefit legislators as they look to improve future electoral returns. We field a nationally representative survey experiment to estimate the effect of credit-claiming and pork-busting messages on the perceived effectiveness, fiscal responsibility, and overall approval of an unnamed member of Congress. We find that respondents are likely to penalize the representative's approval assessment when presented with an out-party message strategy. Conversely, respondents are likely to increase the representative's personal trait assessments when presented with an in-party message strategy. We expand on these results in an additional analysis and find that these trends persist when controlling for other partisan and demographic factors. We discuss our results in light of traditional expectations, potential mechanisms, and future directions for related research.
</details>

### Working Papers

"Does the Medium Change the Message? Topics and Context In Five Venues of Congressional Communication." with Rachel Blum, Jon Green, Diana Jordan, and Kelsey Shoub.

"Public Support for Congressional Candidates Who Use Campaign Funds for Childcare." with Joy D. Rhodes, Peter T. McLaughlin, H Benjamin Ashton III, Rachel Blum, Charles J. Finnocchiaro, and Michael H. Crespin.

"Schooling Reassignments and the Politics of School Desegregation." with Deven Carlson, James Carter III, Thurston Domina, Matthew Lenard, and Rachel Perera.
<a href="https://edworkingpapers.com/sites/default/files/ai25-1150.pdf" target="_blank">{{< ai open-access size=xl color="#505A68" >}}</a>